export const data = [
    {id: 0, title: "Welcome To Learn", link: "welcome-to-learn-verified", lab: false },
    {id: 1, title: "Navigating Curriculum On Learn", link: "prework-intro-navigating-curriculum-on-learn-ide", lab: false },
    {id: 2, title: "Ask A Question", link: "prework-intro-ask-a-question", lab: false },
    {id: 3, title: "Introduction To Version Control", link: "git-version-control-introduction-to-version-control", lab: false },
    {id: 4, title: "Git Version Control Basics", link: "git-version-control-git-basics", lab: false },
    {id: 5, title: "Getting Code With Git ", link: "git-version-control-getting-code-with-git", lab: false },
    {id: 6, title: "Pushing Code With Git", link: "git-version-control-pushing-code-with-git", lab: false },
    {id: 7, title: "Git Basics Lab", link: "git-basics-lab-v-000", lab: true },
    {id: 8, title: "Thinking Ahead",  link: "careers-online-presence-github", lab: false },
    {id: 9, title: "GitHub Pull Request Basics",  link: "github-pull-request-basics", lab: false },
    {id: 10, title: "Git Collaboration",  link: "git-collaboration-readme", lab: false },
    {id: 11, title: "Git Collaboration Quiz",  link: "git-collaboration-quiz", lab: false },
    {id: 12, title: "Git Basics Quiz",  link: "git-github-learn-quiz", lab: false },
    {id: 13, title: "TDD Rspec And Learn",  link: "intro-to-tdd-rspec-and-learn-v-000", lab: true },
    {id: 14, title: "Intro to Tic Tac Toe",  link: "intro-to-tic-tac-toe-rb", lab: false },
    {id: 15, title: "MINSWAN- Yukihuro Matsumoto",  link: "matz-readme", lab: false },
    {id: 16, title: "What is a Program?",  link: "ruby-lecture-intro-what-is-a-program", lab: false },
    {id: 17, title: "Hello World",  link: "hello-world-ruby-v-000", lab: true },
    {id: 18, title: "Intro to IRB",  link: "irb-readme", lab: false },
    {id: 19, title: "Reading Error Messages",  link: "ruby-lecture-reading-error-messages-v-000", lab: true },
    {id: 20, title: "About Variable Assignment", link: "variable-readme", lab: false },
    {id: 21, title: "Variable Assignment Lab", link: "ruby-variable-assignment-v-000", lab: true },
]