export const data = [
    {id: 0, link: "https://github.com/learn-co-curriculum/welcome-to-learn-verified", lab: false },
    {id: 1, link: "https://github.com/learn-co-curriculum/prework-intro-navigating-curriculum-on-learn-ide", lab: false },
    {id: 2, link: "https://github.com/learn-co-curriculum/prework-intro-ask-a-question", lab: false },
    {id: 3, link: "https://github.com/learn-co-curriculum/git-version-control-introduction-to-version-control", lab: false },
    {id: 4, link: "https://github.com/learn-co-curriculum/git-version-control-git-basics", lab: false },
    {id: 5, link: "https://github.com/learn-co-curriculum/git-version-control-getting-code-with-git", lab: false },
    {id: 6, link: "https://github.com/learn-co-curriculum/git-version-control-pushing-code-with-git", lab: false },
    {id: 7, link: "https://github.com/learn-co-students/git-basics-lab-v-000", lab: true },
    {id: 8, link: "https://github.com/learn-co-curriculum/careers-online-presence-github", lab: false },
    {id: 9, link: "https://github.com/learn-co-curriculum/github-pull-request-basics", lab: false },
    {id: 10, link: "https://github.com/learn-co-curriculum/git-collaboration-readme", lab: false },
    {id: 11, link: "https://github.com/learn-co-curriculum/git-collaboration-quiz", lab: false },
    {id: 12, link: "https://github.com/learn-co-curriculum/git-github-learn-quiz", lab: false },
    {id: 13, link: "https://github.com/learn-co-students/intro-to-tdd-rspec-and-learn-v-000", lab: true },
    {id: 14, link: "https://github.com/learn-co-curriculum/intro-to-tic-tac-toe-rb", lab: false },
    {id: 15, link: "https://github.com/learn-co-curriculum/matz-readme", lab: false },
    {id: 16, link: "https://github.com/learn-co-curriculum/ruby-lecture-intro-what-is-a-program", lab: false },
    {id: 17, link: "https://github.com/learn-co-students/hello-world-ruby-v-000", lab: true },
    {id: 18, link: "https://github.com/learn-co-curriculum/irb-readme", lab: false },
    {id: 19, link: "https://github.com/learn-co-students/ruby-lecture-reading-error-messages-v-000", lab: true },
]