export const lessons = [
  {
    id: 0,
    title: "Welcome To Learn",
    url: "welcome-to-learn-verified",
    lab: false,
  },
  {
    id: 1,
    title: "Navigating Curriculum On Learn",
    url: "prework-intro-navigating-curriculum-on-learn-ide",
    lab: false,
  },
  {
    id: 2,
    title: "Ask A Question",
    url: "prework-intro-ask-a-question",
    lab: false,
  },
  {
    id: 3,
    title: "Video: Welcome To Learn",
    url: "prework-videos-welcome-to-learn",
    lab: false,
  },
  {
    id: 4,
    title: "Introduction To Version Control",
    url: "git-version-control-introduction-to-version-control",
    lab: false,
  },
  {
    id: 5,
    title: "Git Version Control Basics",
    url: "git-version-control-git-basics",
    lab: false,
  },
  {
    id: 6,
    title: "Getting Code With Git",
    url: "git-version-control-getting-code-with-git",
    lab: false,
  },
  {
    id: 7,
    title: "Pushing Code with Git",
    url: "git-version-control-pushing-code-with-git",
    lab: false,
  },
  {
    id: 8,
    title: "Git Basics Lab",
    url: "git-basics-lab-v-000",
    lab: true,
  },
  {
    id: 9,
    title: "Thinking Ahead: GitHub as Career Differentiator",
    url:"careers-online-presence-github",
    lab: false,
  },
  {
    id: 10,
    title: "GitHub Pull Requests Basics",
    url: "github-pull-request-basics",
    lab: false,
  },
  {
    id: 11,
    title: "Git Collaboration",
    url: "git-collaboration-readme",
    lab: false,
  },
  {
    id: 12,
    title: "Git Collaboration Quiz",
    url: "git-collaboration-quiz",
    lab: false,
  },
  {
    id: 13,
    title: "Git Basics Quiz",
    url: "git-github-learn-quiz",
    lab: false,
  },
  {
    id: 14,
    title: "TDD Rspec and Learn",
    url: "intro-to-tdd-rspec-and-learn-v-000",
    lab: true,
  },
  {
    id: 15,
    title: "Intro to Tic Tac Toe",
    url: "intro-to-tic-tac-toe-rb",
    lab: false,
  },
  {
    id: 16,
    title: "MINSWAN- Yukihuro Matsumoto",
    url: "matz-readme",
    lab: false,
  },
  {
    id: 17,
    title: "What is a Program?",
    url: "ruby-lecture-intro-what-is-a-program",
    lab: false,
  },
  {
    id: 18,
    title: "Hello World",
    url: "hello-world-ruby-v-000",
    lab: true,
  },
  {
    id: 19,
    title: "Video: Environment Overview",
    url: "prework-videos-environment-overview",
    lab: false,
  },
  {
    id: 20,
    title: "Intro to IRB",
    url: "irb-readme",
    lab: false,
  },
  {
    id: 21,
    title: "Video: IRB",
    url: "prework-videos-irb",
    lab: false,
  },
  {
    id: 22,
    title: "Reading Error Messages",
    url: "ruby-lecture-reading-error-messages-v-000",
    lab: true,
  },
  {
    id: 23,
    title: "Video: Error Messages",
    url: "prework-videos-error-messages",
    lab: false,
  },
  {
    id: 24,
    title: "About Variable Assignment",
    url: "variable-readme",
    lab: false,
  },
  {
    id: 25,
    title: "Video: Variable Assignment",
    url: "prework-videos-variable-assignment",
    lab: false,
  },
  {
    id: 26,
    title: "Variable Assignment Lab",
    url: "ruby-variable-assignment-v-000",
    lab: true,
  },
  {
    id: 27,
    title: "Ruby Data Types",
    url: "",
    lab: false,
  },
  {
    id: 28,
    title: "Video: Ruby Data Types",
    url: "",
    lab: false,
  },
  {
    id: 29,
    title: "Array Basics",
    url: "",
    lab: false,
  },
  {
    id: 30,
    title: "Tic Tac Toe Board",
    url: "ttt-2-board-rb-v-000",
    lab: true,
  },
  {
    id: 31,
    title: "Intro To Tdd Rspec And Learn",
    url: "intro-to-tdd-rspec-and-learn-v-000",
    lab: true,
  },
  {
    id: 32,
    title: "Video: Intro To Tdd Rspec And Learn",
    url: "prework-videos-intro-to-tests-v-000",
    lab: true,
  },
  {
    id: 33,
    title: "Intro To Methods",
    url: "ruby-methods-readme-v-000",
    lab: true,
  },
  {
    id: 34,
    title: "String Interpolation",
    url: "interpolation-readme",
    lab: false,
  },
  {
    id: 35,
    title: "Puts and Return",
    url: "puts-print-and-return-readme",
    lab: false,
  },
  {
    id: 36,
    title: "Display Tic Tac Toe Board Example",
    url: "ttt-3-display_board-example-v-000",
    lab: true,
  },
  {
    id: 37,
    title: "Methods and Arguments",
    url: "ruby-arguments-readme",
    lab: false,
  },
  {
    id: 38,
    title: "Video: Methods and Arguments",
    url: "prework-videos-methods-and-arguments",
    lab: false,
  },
  {
    id: 39,
    title: "Default Arguments",
    url: "methods-default-arguments",
    lab: false,
  },
  {
    id: 40,
    title: "Say Hello",
    url: "say-hello-ruby-v-000",
    lab: true,
  },
  {
    id: 41,
    title: "Interpolation Super Power",
    url: "interpolation-super-power-v-000",
    lab: true,
  },
  {
    id: 42,
    title: "Display Tic Tac Toe Board",
    url: "ttt-4-display-board-rb-v-000",
    lab: true,
  },
  {
    id: 43,
    title: "Intro to CLI Applications",
    url: "intro-to-cli-applications",
    lab: false,
  },
  {
    id: 44,
    title: "CLI Applications in Ruby",
    url: "ruby-cli-applications-readme",
    lab: false,
  },
  {
    id: 45,
    title: "gets CLI Input",
    url: "ruby-gets-input-v-000",
    lab: true,
  },
  {
    id: 46,
    title: "Greeting CLI Lab",
    url: "greeting-cli-v-000",
    lab: true,
  },
  {
    id: 47,
    title: "Tic Tac Toe Move",
    url: "ttt-5-move-rb-v-000",
    lab: true,
  },
  {
    id: 48,
    title: "Truthiness",
    url: "truthiness-in-ruby-readme",
    lab: false,
  },
  {
    id: 49,
    title: "Booleans",
    url: "booleans-ruby-readme",
    lab: false,
  },
  {
    id: 50,
    title: "About Ruby Conditionals",
    url: "conditional-readme",
    lab: false,
  },
  {
    id: 51,
    title: "Rspec Fizzbuzz",
    url: "rspec-fizzbuzz-v-000.git",
    lab: true,
  },
  {
    id: 52,
    title: "Tic Tac Toe Position Taken",
    url: "",
    lab: true,
  },
  {
    id: 53,
    title: "Video: Writing Dynamic Programs",
    url: "",
    lab: false,
  },
  {
    id: 54,
    title: "Valid Tic Tac Toe Move",
    url: "",
    lab: true,
  },
  {
    id: 55,
    title: "Intro to Loops",
    url: "",
    lab: false,
  },
  {
    id: 56,
    title: "Loops",
    url: "",
    lab: false,
  },
  {
    id: 57,
    title: "While and Until Loops",
    url: "",
    lab: false,
  },
  {
    id: 58,
    title: "While and Until Loops Lab",
    url: "",
    lab: true,
  },
  {
    id: 59,
    title: "Tic Tac Toe Turn",
    url: "",
    lab: true,
  },
  {
    id: 60,
    title: "Tic Tac Toe Play Loop",
    url: "",
    lab: true,
  },
  {
    id: 61,
    title: "Iteration and Abstraction",
    url: "",
    lab: false,
  },
  {
    id: 62,
    title: "Intro to Ruby Iterators",
    url: "",
    lab: false,
  },
  {
    id: 63,
    title: "Tic Tac Toe Current Player",
    url: "",
    lab: true,
  },
  {
    id: 64,
    title: "Nested Arrays",
    url: "",
    lab: false,
  },
  {
    id: 65,
    title: "Boolean Enumerables",
    url: "",
    lab: false,
  },
  {
    id: 66,
    title: "Search Enumerables",
    url: "",
    lab: false,
  },
  {
    id: 67,
    title: "Tic Tac Toe Game Status",
    url: "",
    lab: true,
  },
  {
    id: 68,
    title: "Tic Tac Toe in Ruby",
    url: "",
    lab: true,
  },
  {
    id: 69,
    title: "Transitioning from Ruby to HTML",
    url: "",
    lab: false,
  },
  {
    id: 70,
    title: "A Quick Tour of the Web",
    url: "",
    lab: false,
  },
  {
    id: 71,
    title: "Welcome to HTML",
    url: "",
    lab: false,
  },
  {
    id: 72,
    title: "Files and Filetypes",
    url: "",
    lab: false,
  },
  {
    id: 73,
    title: "Experiencing HTML Lab",
    url: "",
    lab: true,
  },
  {
    id: 74,
    title: "Crafting HTML Documents",
    url: "",
    lab: false,
  },
  {
    id: 75,
    title: "HTML Introduction",
    url: "",
    lab: false,
  },
  {
    id: 76,
    title: "",
    url: "",
    lab: true,
  },
  {
    id: 77,
    title: "",
    url: "",
    lab: true,
  },
  {
    id: 78,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 79,
    title: "",
    url: "",
    lab: true,
  },
  {
    id: 80,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 81,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 82,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 83,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 84,
    title: "",
    url: "",
    lab: true,
  },
  {
    id: 85,
    title: "Transitioning Back to Ruby",
    url: "",
    lab: false,
  },
  {
    id: 86,

    title: "What's a Pattern",
    url: "",
    lab: false,
  },
  {
    id: 87,
    title: "Regex Basics",
    url: "",
    lab: false,
  },
  {
    id: 88,
    title: "Ruby Methods with Regex",
    url: "",
    lab: false,
  },
  {
    id: 89,
    title: "Regex Lab",
    url: "",
    lab: true,
  },
  {
    id: 90,
    title: "About Variable Assignment",
    url: "variable-readme.git",
    lab: false,
  },
  {
    id: 91,
    title: "Variable Assignment Lab",
    url:"ruby-variable-assignment-v-000.git",
    lab: true,
  },
  {
    id: 92,
    title: "String Interpolation",
    url: "",
    lab: false,
  },
  {
    id: 93,
    title: "Defining Methods",
    url: "ruby-methods-readme-v-000.git",
    lab: true,
  },
  {
    id: 94,
    title: "Methods and Arguments",
    url: "",
    lab: false,
  },
  {
    id: 95,
    title: "Methods and Arguments Lab",
    url: "method-arguments-lab-v-000.git",
    lab: true,
  },
  {
    id: 96,
    title: "Methods and Default Arguments",
    url: "",
    lab: false,
  },
  {
    id: 97,
    title: "Methods and Default Arguments Lab",
    url: "say-hello-ruby-v-000.git",
    lab: true,
  },
  {
    id: 98,
    title: "Return Values",
    url: "",
    lab: false,
  },
  {
    id: 99,
    title: "Return Values Lab",
    url: "parrot-ruby-v-000.git",
    lab: true,
  },
  {
    id: 100,
    title: "Debugging with Pry",
    url: "debugging-with-pry-v-000.git",
    lab: true,
  },
  {
    id: 101,
    title: "Method Scope",
    url: "",
    lab: false,
  },
  {
    id: 102,
    title: "Method Scope Lab",
    url: "method-scope-lab-v-000.git",
    lab: true,
  },
  {
    id: 103,
    title: "Booleans and Truthiness in Ruby",
    url: "",
    lab: false,
  },
  {
    id: 104,
    title: "Boolean Operators",
    url: "",
    lab: false,
  },
  {
    id: 105,
    title: "Truthiness Code Challenge",
    url: "",
    lab: false,
  },
  {
    id: 106,
    title: "If Statements",
    url: "",
    lab: false,
  },
  {
    id: 107,
    title: "If Statements Lab",
    url: "speaking-grandma-v-000.git",
    lab: true,
  },
  {
    id: 108,
    title: "Ternary Operators and Statement Modifiers",
    url: "operators-v-000.git",
    lab: true,
  },
  {
    id: 109,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 110,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 111,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 112,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 113,
    title: "Intro to Loops",
    url: "",
    lab: false,
  },
  {
    id: 114,
    title: "Looping",
    url: "",
    lab: false,
  },
  {
    id: 115,
    title: "Looping Lab",
    url: "",
    lab: false,
  },
  {
    id: 116,
    title: "Times",
    url: "",
    lab: true,
  },
  {
    id: 117,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 118,
    title: "",
    url: "",
    lab: false,
  },
  {
    id: 119,
    title: "While and Until Loops Lab",
    url: "",
    lab: true,
  },
  {
    id: 120,
    title: "Countdown to Midnight Lab",
    url: "",
    lab: true,
  },
  {
    id: 121,
    title: "Intro to Arrays",
    url: "",
    lab: false,
  },
  {
    id: 122,
    title: "Using Arrays",
    url: "",
    lab: false,
  },
  {
    id: 123,
    title: "Using Arrays Lab",
    url: "",
    lab: true,
  },
  {
    id: 124,
    title: "Arrays and Methods",
    url: "",
    lab: false,
  },
  {
    id: 125,
    title: "Arrays and Methods Lab",
    url: "",
    lab: true,
  },
  {
    id: 126,
    title: "Video: Intro to Arrays",
    url: "",
    lab: false,
  },
  {
    id: 127,
    title: "Iteration and Abstraction",
    url: "",
    lab: false,
  },
  {
    id: 128,
    title: "Intro to Ruby Iterators",
    url: "",
    lab: false,
  },
  {
    id: 129,
    title: "Square Array Lab",
    url: "",
    lab: true,
  },
  {
    id: 130,
    title: "Badges and Schedules Lab",
    url: "",
    lab: true,
  },
  {
    id: 131,
    title: "Oxford Comma Lab",
    url: "",
    lab: true,
  },
  {
    id: 132,
    title: "Deli Counter Lab",
    url: "",
    lab: true,
  },
  {
    id: 133,
    title: "Collect and Return Values",
    url: "",
    lab: false,
  },
  {
    id: 134,
    title: "Reverse Each Word Lab",
    url: "",
    lab: true,
  },
  {
    id: 135,
    title: "Yield and Blocks",
    url: "",
    lab: true,
  },
  {
    id: 136,
    title: "Yield and Blocks",
    url: "",
    lab: true,
  },
  {
    id: 137,
    title: "Each Lab",
    url: "",
    lab: true,
  },
];
